# Example .pre-commit-config.yaml for projects using this hook
repos:
  # Use the distributed hook from a GitHub repository
  - repo: https://github.com/your-org/pylint-ruff-sync
    rev: v0.1.0  # Use the latest version
    hooks:
      - id: pylint-ruff-sync
        # Optional: Add custom rules by code or name
        args: [
          "--custom-enable", "C0103", "invalid-name",  # Enable specific rules
          "--custom-disable", "R0903", "too-few-public-methods"  # Disable specific rules
        ]
        
  # Optional: Also run ruff and other tools
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--strict] 