version: "0.2"
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  - .config/requirements*
  - \.*
  - cspell.config.yaml
  - pyproject.toml
  - src/pylint_ruff_sync/data/ruff_implemented_rules.json

languageSettings:
  - languageId: python
    allowCompoundWords: false

words:
  - mypy
  - pytest
  - cidrblock
  - antonagestam
  - asyncfunctiondef
  - setuptools
  - charliermarsh
  - functiondef
  - testpaths
  - tomlsort
  - Mypy
  - PYPI
  - pycache
  - codz
  - sdist
  - htmlcov
  - nosetests
  - webassets
  - Scrapy
  - scrapy
  - pybuilder
  - ipynb
  - ipython
  - pyenv
  - pipenv
  - pypa
  - Pipfile
  - pixi
  - Pixi
  - venv
  - Connor
  - pyflow
  - pypackages
  - celerybeat
  - envrc
  - Spyder
  - spyderproject
  - spyproject
  - ropeproject
  - mkdocs
  - dmypy
  - pytype
  - Cython
  - cython
  - Abstra
  - abstra
  - pypirc
  - cursorignore
  - cursorindexingignore
  - Marimo
  - marimo
  - Streamlit
  - streamlit
  - beautifulsoup
  - commitlint
  - pydoclint
  - typevar
  - classmethod
  - Metaclass
  - maxsplit
  - toplevel
  - dunder
  - nonlocal
  - repr
  - notimplemented
  - kwoa
  - metaclass
  - unhashable
  - singledispatch
  - singledispatchmethod
  - aenter
  - aexit
  - staticmethod
  - contextmanager
  - popen
  - maxsize
  - dependendices
  - monkeypatch
  - levelname
