version: "0.2"
language: "en"
words:
  - pylint
  - ruff
  - pyproject
  - toml
  - kwargs
  - dataclass
  - isinstance
  - fstring
  - multifile
  - booleaness
  - falsey
  - getnewargs
  - simplifiable
  - evals
  - vararg
  - kwarg
  - preexec
