[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = ["pytest>=8.3.5", "ruff>=0.12.3"]
test = ["mypy>=1.16.1", "pydoclint>=0.5.11", "types-requests>=2.32.4.20250611"]

[project]
dependencies = [
  "requests>=2.28.0",
  "beautifulsoup4>=4.11.0",
  "pylint>=2.15.0",
  "toml-sort>=0.24.0"
]
description = "Precommit hook to sync pylint configuration with ruff implementation status"
name = "pylint-ruff-sync"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[project.optional-dependencies]
test = [
  "pre-commit>=2.20.0",
  "ruff>=0.1.6",
  "mypy>=1.7.1",
  "types-requests>=2.28.0",
  "types-beautifulsoup4>=4.11.0",
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0"
]

[project.scripts]
pylint-ruff-sync = "pylint_ruff_sync.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/pylint_ruff_sync"]

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
python_version = "3.11"
strict = true
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pydoclint]
allow-init-docstring = true
arg-type-hints-in-docstring = false
baseline = ".config/pydoclint-baseline.txt"
check-return-types = false
exclude = "\\.git|\\.tox|\\.venv|build|out|venv"
should-document-private-class-attributes = true
show-filenames-in-every-violation-message = true
skip-checking-short-docstrings = false
style = "google"

[tool.pylint.basic]
good-names = "i,j,k,ex,Run,_,f,fh"
ignore = ["_version.py"]
jobs = 0
no-docstring-rgx = "__.*__"

[tool.pylint.classes]
max-attributes = 20
min-public-methods = 0

[tool.pylint.format]
max-line-length = 100

[tool.pylint.messages_control]
disable = ["all", "locally-disabled", "suppressed-message"]
enable = [
  "C0104", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0104.html
  "C0117", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0117.html
  "C0200", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0200.html
  "C0203", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0203.html
  "C0204", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0204.html
  "C0209", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0209.html
  "C0302", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0302.html
  "C0325", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0325.html
  "C0327", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0327.html
  "C0328", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0328.html
  "C0401", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0401.html
  "C0402", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0402.html
  "C0403", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/0403.html
  "C1803", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/1803.html
  "C1804", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/1804.html
  "C1805", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/1805.html
  "C2503", # https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/2503.html
  "E0011", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0011.html
  "E0013", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0013.html
  "E0014", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0014.html
  "E0015", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0015.html
  "E0108", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0108.html
  "E0110", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0110.html
  "E0111", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0111.html
  "E0113", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0113.html
  "E0119", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0119.html
  "E0202", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0202.html
  "E0203", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0203.html
  "E0211", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0211.html
  "E0236", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0236.html
  "E0238", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0238.html
  "E0239", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0239.html
  "E0240", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0240.html
  "E0242", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0242.html
  "E0243", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0243.html
  "E0244", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0244.html
  "E0245", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0245.html
  "E0301", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0301.html
  "E0306", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0306.html
  "E0307", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0307.html
  "E0310", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0310.html
  "E0311", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0311.html
  "E0312", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0312.html
  "E0313", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0313.html
  "E0401", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0401.html
  "E0606", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0606.html
  "E0611", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0611.html
  "E0633", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0633.html
  "E0701", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0701.html
  "E0702", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0702.html
  "E0705", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0705.html
  "E0710", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0710.html
  "E0712", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0712.html
  "E1003", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1003.html
  "E1101", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1101.html
  "E1102", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1102.html
  "E1111", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1111.html
  "E1120", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1120.html
  "E1121", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1121.html
  "E1123", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1123.html
  "E1124", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1124.html
  "E1125", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1125.html
  "E1126", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1126.html
  "E1127", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1127.html
  "E1128", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1128.html
  "E1129", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1129.html
  "E1133", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1133.html
  "E1134", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1134.html
  "E1135", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1135.html
  "E1136", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1136.html
  "E1137", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1137.html
  "E1138", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1138.html
  "E1139", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1139.html
  "E1141", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1141.html
  "E1143", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1143.html
  "E1144", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1144.html
  "E1200", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1200.html
  "E1201", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1201.html
  "E1507", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1507.html
  "E1701", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/1701.html
  "E2501", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/2501.html
  "E2511", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/2511.html
  "E3102", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/3102.html
  "E3701", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/3701.html
  "E4702", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/4702.html
  "F0002", # https://pylint.readthedocs.io/en/stable/user_guide/messages/fatal/0002.html
  "F0010", # https://pylint.readthedocs.io/en/stable/user_guide/messages/fatal/0010.html
  "F0011", # https://pylint.readthedocs.io/en/stable/user_guide/messages/fatal/0011.html
  "F0202", # https://pylint.readthedocs.io/en/stable/user_guide/messages/fatal/0202.html
  "I0001", # https://pylint.readthedocs.io/en/stable/user_guide/messages/info/0001.html
  "I0010", # https://pylint.readthedocs.io/en/stable/user_guide/messages/info/0010.html
  "I0013", # https://pylint.readthedocs.io/en/stable/user_guide/messages/info/0013.html
  "I0021", # https://pylint.readthedocs.io/en/stable/user_guide/messages/info/0021.html
  "I0022", # https://pylint.readthedocs.io/en/stable/user_guide/messages/info/0022.html
  "I1101", # https://pylint.readthedocs.io/en/stable/user_guide/messages/info/1101.html
  "R0022", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/0022.html
  "R0401", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/0401.html
  "R0801", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/0801.html
  "R0901", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/0901.html
  "R0902", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/0902.html
  "R0903", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/0903.html
  "R1706", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1706.html
  "R1708", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1708.html
  "R1709", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1709.html
  "R1712", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1712.html
  "R1713", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1713.html
  "R1716", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1716.html
  "R1726", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1726.html
  "R1727", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1727.html
  "R1736", # https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/1736.html
  "W0012", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0012.html
  "W0101", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0101.html
  "W0105", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0105.html
  "W0124", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0124.html
  "W0125", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0125.html
  "W0126", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0126.html
  "W0128", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0128.html
  "W0134", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0134.html
  "W0135", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0135.html
  "W0143", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0143.html
  "W0201", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0201.html
  "W0213", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0213.html
  "W0221", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0221.html
  "W0222", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0222.html
  "W0223", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0223.html
  "W0231", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0231.html
  "W0233", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0233.html
  "W0236", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0236.html
  "W0237", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0237.html
  "W0238", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0238.html
  "W0239", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0239.html
  "W0240", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0240.html
  "W0244", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0244.html
  "W0246", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0246.html
  "W0407", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0407.html
  "W0416", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0416.html
  "W0601", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0601.html
  "W0614", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0614.html
  "W0621", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0621.html
  "W0631", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0631.html
  "W0632", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0632.html
  "W0641", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0641.html
  "W0642", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0642.html
  "W0644", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0644.html
  "W0715", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0715.html
  "W0716", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/0716.html
  "W1114", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1114.html
  "W1115", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1115.html
  "W1116", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1116.html
  "W1117", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1117.html
  "W1300", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1300.html
  "W1306", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1306.html
  "W1307", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1307.html
  "W1308", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1308.html
  "W1402", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1402.html
  "W1503", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1503.html
  "W1506", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1506.html
  "W1507", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1507.html
  "W2601", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/2601.html
  "W2602", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/2602.html
  "W2603", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/2603.html
  "W2604", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/2604.html
  "W2605", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/2605.html
  "W2606", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/2606.html
  "W3101", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/3101.html
  "W3601", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/3601.html
  "W4701", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/4701.html
  "W4901", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/4901.html
  "W4902", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/4902.html
  "W4903", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/4903.html
  "W4904", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/4904.html
  "W4905", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/4905.html
  "W4906", # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/4906.html
  "E0106", # https://pylint.readthedocs.io/en/stable/user_guide/messages/error/0106.html
  "W1502" # https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/1502.html
]

[tool.pylint.reports]
output-format = "colorized"

[tool.pylint.similarities]
ignore-comments = true
ignore-docstrings = true
ignore-imports = true
min-similarity-lines = 20

[tool.ruff]
fix = true
line-length = 88
target-version = "py311"

[tool.ruff.lint]
ignore = ["D203", "D211", "D213", "COM812"]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101", "SLF001", "EXE001"]
